#! /bin/sh

# launching utility apps
sxhkd &
picom -b
wal -R

# bspwm config
MON_COUNT="$(xrandr | grep -E '\<connected\>' | wc -l)"

if [[ $MON_COUNT -gt 1 ]]; then
	# Multiple monitors
	bspc monitor 'eDP-1' -d desktop
	bspc monitor 'HDMI-2' -f -d code browse desktop music
else
	bspc monitor 'eDP-1' -d code browse desktop music
fi

bspc config border_width					3
bspc config focused_border_color	'#E0E0E0'
bspc config window_gap						20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'firefox:Navigator' desktop=browse private=on
bspc rule -a Zathura state=tiled

dunst &
firefox &
# Launch music notifier
~/scripts/music.py &> /dev/null &
~/.config/polybar/launch.sh
xdo above -t $(xdo id -n root) $(xdo id -n polybar)

xautolock -time 5 -locker "~/scripts/lock" -corners 00-0 -cornersize 5 -killtime 5 -killer "systemctl suspend"

