#! /bin/sh

# launching utility apps
sxhkd &
compton -b --config ~/.config/compton.conf
feh --bg-fill ~/wallpapers/Jupiter.jpg

# bspwm config
MONITORS="$(xrandr | grep -E '\<connected\>' | cut -d' ' -f1)"

for monitor in $MONITORS; do
	bspc monitor $monitor -d code browse desktop music
done

bspc config border_width					4
bspc config focused_border_color	'#E0E0E0'
bspc config window_gap						20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox focus=on
bspc rule -a Gvim state=floating
bspc rule -a Galculator state=floating
bspc rule -a Zathura state=tiled

dunst &
~/.config/polybar/launch.sh
xdo above -t $(xdo id -n root) $(xdo id -n polybar)

xautolock -time 3 -locker "~/scripts/lock" -corners 0-00 -killtime 3 -killer "systemctl suspend"
