#! /bin/sh

# launching utility apps
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b
# Set the wallpaper
~/.fehbg &

bspc monitor -d code browse desktop music

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color	'#E0E0E0'
bspc config presel_feedback_color "$color1"

bspc config border_width 3
bspc config window_gap 15

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'firefox:Navigator' desktop=browse private=on
bspc rule -a Zathura state=tiled

firefox &
${HOME}/.config/dunst/launch.sh
${HOME}/.config/polybar/launch.sh
