#!/bin/zsh

# Useful aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='vim --servername VIM'
alias spotify='spotify --force-device-scale-factor=1.25'
alias fuck='sudo $(fc -ln -1)'

# Alias git (alias) to g(alias)
list=(${${${(0)"$(git config -z --get-regexp '^alias\.')"}#alias.}%$'\n'*})
for al in $list; do
	alias "g${al}"="git $al"
done
